<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
	<Authors>Elisabeth Felina Bertram et al</Authors>
	<Company>Bertram Enterprises LLC dba TuringTrader.com</Company>
    <Product>TuringTrader</Product>
    <Description>Open-source backtesting engine and trading simulator</Description>
    <PackageProjectUrl>https://www.turingtrader.org/</PackageProjectUrl>
    <Copyright>Copyright (c) 2011-2025, Bertram Enterprises LLC dba TuringTrader.com</Copyright>
    <RepositoryUrl>https://github.com/fbertram/TuringTrader/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Platforms>x64</Platforms>
    <RootNamespace>TuringTrader</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DocumentationFile>TuringTrader.Simulator.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DocumentationFile>TuringTrader.Simulator.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Simulator\v2\Core\FloatWrapper.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TuringTrader\GitVersion.cs" Link="Simulator\v2\Core\GitVersion.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Simulator\v2\Core\FloatWrapper.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IB.CSharpAPI">
      <HintPath>..\packages\IB.CSharpAPI.9.72.18\IB.CSharpAPI.dll</HintPath>
    </Reference>
    <Reference Include="NorgateData.DataAccess.API">
      <HintPath>..\..\..\..\..\..\Program Files\Norgate Data Updater\bin\NorgateData.DataAccess.API.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NorgateData.DataAccess.Core">
      <HintPath>..\..\..\..\..\..\Program Files\Norgate Data Updater\bin\NorgateData.DataAccess.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
