---
title: "`r format(Sys.time(), '%b %d, %Y, %H:%M:%S')`"
output:
  html_document:
    toc: true
    theme: united
---

<!--
title: "test"
author: "felix"
date: "`r format(Sys.time(), '%b %d, %Y, %H:%M:%S')`"
params:
  test: false
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# command-line arguments come in pairs: the plot name, and the csv with the data
args <- split(commandArgs(trailingOnly = TRUE), 1:2)

# colors to use for the plots. as the first plot uses column 2, 
# the first value is used for the grid
colors <- c('gray60', 'black', 'red', 'green', 'blue', 'orange', 'cyan', 'darkorchid', 'deeppink', 'gold', 'orangered', 'purple', 'slategray', 'turquoise', 'brown', 'tan')

# function to convert to date
# also see here: https://stackoverflow.com/questions/18178451/is-there-a-way-to-check-if-a-column-is-a-date-in-r
to.date <- function(x) as.Date(as.character(x), format="%m/%d/%Y")

# function to determine if a column has dates in it
is.date <- function(x) (!all(is.na(to.date(x))))

# function to create a pretty plot
create.plot <- function(title, df) {
	# plot the 1st series
	plot(df[,1], df[,2], type = 'l', axes = FALSE, col = colors[[2]], xlab = '', ylab = '', main = '')

	# plot the 2nd and following series
	if (ncol(df) >= 3) {
		for (j in 3:ncol(df)) {
			lines(df[,1], df[,j], col = colors[[j]])
		}
	}

	# set the labels for x and y axis
	if (sapply(df, class)[1] == "Date") {
		axis.Date(1, at = seq(min(df[,1]), max(df[,1]), by="3 mon"), format = '%m-%Y', cex.axis = 0.7)
		abline(v = seq(min(df[,1]), max(df[,1]), by = "3 month") , col = colors[[1]], lty = "dotted")
		grid(nx = NA, ny = NULL, col = colors[[1]], lty = "dotted")
	} else {
		axis(1, labels = TRUE)
		grid(col = colors[[1]], lty = "dotted")
	}
	axis(2, labels = TRUE)

	# set title, legend, and box
	title(main = title, xlab = colnames(df)[1])
	legend("topleft", legend=colnames(df)[2:ncol(df)], col=colors[2:ncol(df)], lty=1, lwd=2, cex=0.9, bty='n')
	box()
}

# function to create a pretty table
create.table <- function(title, df) {
	library(knitr)
	kable(df, caption = title)
}

# function to handle a single plot/ table
create.plot.or.table <- function(title, csv) {
	df <- read.csv(csv)

	# convert date columns
	fmt <- sapply(df, is.date)
	for (i in 1:ncol(df)) {
		if (fmt[i]) {
			df[,i] <- to.date(df[,i])
		}
	}

	# check for remaining factors
	if (any(sapply(df, is.factor))) {
		create.table(title, df)
	} else {
		create.plot(title, df)
	}
}

```

```{r echo=FALSE, warning=FALSE}
# somehow, creating tables fails if we use a for-loop here
if (length(args[[1]]) >= 1) create.plot.or.table(args[[1]][1], args[[2]][1])
if (length(args[[1]]) >= 2) create.plot.or.table(args[[1]][2], args[[2]][2])
if (length(args[[1]]) >= 3) create.plot.or.table(args[[1]][3], args[[2]][3])
if (length(args[[1]]) >= 4) create.plot.or.table(args[[1]][4], args[[2]][4])
if (length(args[[1]]) >= 5) create.plot.or.table(args[[1]][5], args[[2]][5])
if (length(args[[1]]) >= 6) create.plot.or.table(args[[1]][6], args[[2]][6])
if (length(args[[1]]) >= 7) create.plot.or.table(args[[1]][7], args[[2]][7])
if (length(args[[1]]) >= 8) create.plot.or.table(args[[1]][8], args[[2]][8])
if (length(args[[1]]) >= 9) create.plot.or.table(args[[1]][9], args[[2]][9])
```

Created with TuringTrader.
